const channels = [
  {
    channel: "CanalGaming123",
    follow: true,
    online: true,
    game: "Fortnite",
    viewers: "100",
  },
  {
    channel: "NekoiTuber",
    follow: false,
    online: true,
    game: "Minecraft",
    viewers: "20k",
  },
  {
    channel: "Canal5678",
    follow: true,
    online: false,
    game: "Valorant",
    viewers: "5k",
  },
  {
    channel: "Canal0123",
    follow: false,
    online: true,
    game: "DOTA 2",
    viewers: "10k",
  },
  {
    channel: "TechReview",
    follow: true,
    online: false,
    game: "Fornite",
    viewers: "0",
  },
  {
    channel: "CookingWithSara",
    follow: false,
    online: true,
    game: "Cooking Simulator",
    viewers: "500",
  },
  {
    channel: "MusicMaster88",
    follow: true,
    online: true,
    game: "Music",
    viewers: "200",
  },
  {
    channel: "FitnessFreak101",
    follow: true,
    online: true,
    game: "Fitness Workout",
    viewers: "50",
  },
  {
    channel: "ArtisticVisionary",
    follow: false,
    online: true,
    game: "Art & Design",
    viewers: "150",
  },
  {
    channel: "SportsFanatic22",
    follow: true,
    online: false,
    game: null,
    viewers: "0",
  },
  {
    channel: "TechEnthusiast789",
    follow: false,
    online: true,
    game: "Tech Talks",
    viewers: "100",
  },
  {
    channel: "BookwormReads",
    follow: true,
    online: true,
    game: "Book Reviews",
    viewers: "80",
  },
  {
    channel: "FoodieDelights",
    follow: false,
    online: true,
    game: "Cooking",
    viewers: "200",
  },
  {
    channel: "AnimalLover88",
    follow: false,
    online: false,
    game: null,
    viewers: "0",
  },
];

export default channels;
