const games = [
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/516575-285x380.jpg",
    title: "Valorant",
    views: "100k",
    tags: ["FPS", "Shooter", "Multiplayer"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/27471_IGDB-285x380.jpg",
    title: "Minecraft",
    views: "413k",
    tags: ["MMORPG", "PvE"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/33214-285x380.jpg",
    title: "Fortnite",
    views: "753k",
    tags: ["Shooter", "FPS"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/21779-285x380.jpg",
    title: "League of Legends",
    views: "966k",
    tags: ["Platformer", "Side-scrolling"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/511224-285x380.jpg",
    title: "Apex Legends",
    views: "112k",
    tags: ["Survival", "Horror"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/512710-285x380.jpg",
    title: "Call of Duty",
    views: "980k",
    tags: ["Shooter", "FPS"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/515025-285x380.jpg",
    title: "Overwatch",
    views: "848k",
    tags: ["Platformer", "Side-scrolling"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/30921-285x380.jpg",
    title: "Rocket League",
    views: "922k",
    tags: ["MOBA", "Competitive"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/516575-285x380.jpg",
    title: "Valorant",
    views: "100k",
    tags: ["FPS", "Shooter", "Multiplayer"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/27471_IGDB-285x380.jpg",
    title: "Minecraft",
    views: "413k",
    tags: ["MMORPG", "PvE"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/33214-285x380.jpg",
    title: "Fortnite",
    views: "753k",
    tags: ["Shooter", "FPS"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/21779-285x380.jpg",
    title: "League of Legends",
    views: "966k",
    tags: ["Platformer", "Side-scrolling"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/511224-285x380.jpg",
    title: "Apex Legends",
    views: "112k",
    tags: ["Survival", "Horror"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/512710-285x380.jpg",
    title: "Call of Duty",
    views: "980k",
    tags: ["Shooter", "FPS"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/515025-285x380.jpg",
    title: "Overwatch",
    views: "848k",
    tags: ["Platformer", "Side-scrolling"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/30921-285x380.jpg",
    title: "Rocket League",
    views: "922k",
    tags: ["MOBA", "Competitive"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/516575-285x380.jpg",
    title: "Valorant",
    views: "100k",
    tags: ["FPS", "Shooter", "Multiplayer"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/27471_IGDB-285x380.jpg",
    title: "Minecraft",
    views: "413k",
    tags: ["MMORPG", "PvE"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/33214-285x380.jpg",
    title: "Fortnite",
    views: "753k",
    tags: ["Shooter", "FPS"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/21779-285x380.jpg",
    title: "League of Legends",
    views: "966k",
    tags: ["Platformer", "Side-scrolling"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/511224-285x380.jpg",
    title: "Apex Legends",
    views: "112k",
    tags: ["Survival", "Horror"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/512710-285x380.jpg",
    title: "Call of Duty",
    views: "980k",
    tags: ["Shooter", "FPS"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/515025-285x380.jpg",
    title: "Overwatch",
    views: "848k",
    tags: ["Platformer", "Side-scrolling"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/30921-285x380.jpg",
    title: "Rocket League",
    views: "922k",
    tags: ["MOBA", "Competitive"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/516575-285x380.jpg",
    title: "Valorant",
    views: "100k",
    tags: ["FPS", "Shooter", "Multiplayer"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/27471_IGDB-285x380.jpg",
    title: "Minecraft",
    views: "413k",
    tags: ["MMORPG", "PvE"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/33214-285x380.jpg",
    title: "Fortnite",
    views: "753k",
    tags: ["Shooter", "FPS"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/21779-285x380.jpg",
    title: "League of Legends",
    views: "966k",
    tags: ["Platformer", "Side-scrolling"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/511224-285x380.jpg",
    title: "Apex Legends",
    views: "112k",
    tags: ["Survival", "Horror"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/512710-285x380.jpg",
    title: "Call of Duty",
    views: "980k",
    tags: ["Shooter", "FPS"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/515025-285x380.jpg",
    title: "Overwatch",
    views: "848k",
    tags: ["Platformer", "Side-scrolling"],
  },
  {
    img: "https://static-cdn.jtvnw.net/ttv-boxart/30921-285x380.jpg",
    title: "Rocket League",
    views: "922k",
    tags: ["MOBA", "Competitive"],
  },
];

export default games;
